ALPACA_API_KEY = "PK36CVS85LYROLB8VHYR"
ALPACA_API_SECRET_KEY = "QIkXj1kmgAsAO3ojEnOFF1PcqEvNHzZZUQgDtoYK"

HEADERS = {
    'APCA-API-KEY-ID' : ALPACA_API_KEY,
    'APCA-API-SECRET-KEY' : ALPACA_API_SECRET_KEY
}

APCA_API_BASE_URL = 'https://paper-api.alpaca.markets'